repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.6.5
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix, --config=./backend/pyproject.toml]
          # Run the formatter.
          - id: ruff-format
            args: [--config=./backend/pyproject.toml]