# main.py
from py2ts import generate_ts
from py2ts.data import TSInterface

from beets_flask.importer.states import (
    SerializedSessionState,
)

ts_session = generate_ts(SerializedSessionState)
assert isinstance(ts_session, TSInterface)

prefix = """/* 
 * This file is generated by ../backend/generate_types.py
 * Do not edit this file manually!
 */
"""

with open("../frontend/src/pythonTypes.d.ts", "w") as f:
    f.write(prefix)
    f.write(ts_session.full_str())


print("Typescript types generated successfully!")
