from py2ts.builder import TSBuilder

from beets_flask.database.models.notifications import (
    PushSubscription,
    WebhookSubscription,
)
from beets_flask.disk import Archive, File, FileSystemItem, Folder
from beets_flask.importer.states import (
    SerializedSessionState,
)
from beets_flask.invoker import EnqueueKind
from beets_flask.invoker.enqueue import (
    CandidateChoiceFallback,
    Search,
)
from beets_flask.server.routes.inbox import InboxStats
from beets_flask.server.routes.library.resources import (
    AlbumResponse,
    AlbumResponseExpanded,
    AlbumResponseMinimal,
    AlbumResponseMinimalExpanded,
    ItemResponse,
    ItemResponseMinimal,
)
from beets_flask.server.routes.library.stats import LibraryStats
from beets_flask.server.routes.notifications import PushNotification
from beets_flask.server.websocket.status import (
    FileSystemUpdate,
    FolderStatusUpdate,
    JobStatusUpdate,
)

prefix = """/*
 * This file is generated by ../backend/generate_types.py
 * Do not edit this file manually!
 */
"""

builder = TSBuilder()


# Session state
builder.add(SerializedSessionState)

# ------------------------------- inbox routes ------------------------------- #

# Folder
builder.add(FileSystemItem)
builder.add(File)
builder.add(Archive)
builder.add(Folder)
builder.add(InboxStats)


# Invoker / enqueue
builder.add(EnqueueKind)
builder.add(Search)
builder.add(CandidateChoiceFallback)


# ------------------------------ library routes ------------------------------ #

# Stats
builder.add(LibraryStats)

# Item responses
builder.add(ItemResponse)
builder.add(ItemResponseMinimal)

# Album responses
builder.add(AlbumResponse)
builder.add(AlbumResponseMinimal)
builder.add(AlbumResponseExpanded)
builder.add(AlbumResponseMinimalExpanded)

# ------------------------------ Status updates ------------------------------ #

builder.add(FolderStatusUpdate)
builder.add(JobStatusUpdate)
builder.add(FileSystemUpdate)


builder.save_file("../frontend/src/pythonTypes/index.ts")
print("✅ Typescript types generated successfully!")


# ---------------------------- Push/Notifications ---------------------------- #

# We place all notification related types in another file to keep a cleaner structure
notification_builder = TSBuilder()

notification_builder.add(PushSubscription, exclude={"settings_id"})
notification_builder.add(WebhookSubscription, exclude={"settings_id"})
notification_builder.add(PushNotification)
notification_builder.add(InboxStats)

notification_builder.save_file("../frontend/src/pythonTypes/notifications.ts")
print("✅ Notification types generated successfully!")
