services:
    beets-flask:
        container_name: beets-flask
        hostname: beets-container
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: dev
        image: beets-flask
        restart: unless-stopped
        ports:
            - "5001:5001" # for beets-flask
            - "5173:5173" # for vite dev server
        environment:
            # 502 is default on macos, 1000 on linux
            PUID: 1000
            PGID: 1000
            LOG_LEVEL_BEETSFLASK: DEBUG # this is used for our own logs. (set beets level via the config)
            LOG_LEVEL_OTHERS: WARNING # this is passed python logging basic config (all other modules)
        volumes:
            - /srv/music-stack/beets-flask-test:/config
            - /home/jp_srv/music-library:/library
            - /mnt/storage/music-data/music/sources:/sources
            - ../:/repo/
