# ------------------------------------------------------------------------------------ #
#                                   BEETS GUI CONFIG                                   #
# ------------------------------------------------------------------------------------ #
# Example file, this file was automatically copied to /config/beets-flask/config.yaml.
# Feel free to edit this file to customize the gui configuration.
# Especially the `folders` section in the `inbox` section are important to set up your inbox
# folders. You can add as many folders as you like, but don't forget to volume-map them in
# your docker-compose.yml.

gui:
    num_workers_preview: 4 # how many previews to generate in parallel

    library:
        readonly: no

    tags:
        expand_tags: yes # for tag groups, on page load, show tag details?
        recent_days: 14 # Number of days to consider for the "recent" tag group
        order_by: "name" # how to sort tags within the trag groups: "name" (the album folder basename) | "date_created" | "date_modified"
        show_unchanged_tracks: no # whether to show even unchanged tracks in the preview (interactve import sessions)

    terminal:
        start_path: "/music/inbox" # the directory where to start new terminal sessions

    inbox:
        concat_nested_folders: yes # show multiple folders in one line if they only have one child
        expand_files: no # on page load, show files in (album) folders, or collapse them

        folders: # dont forget to volume-map these folders in your docker-compose.yml
            Lorem:
                name: "Awesome Inbox"
                path: "/music/inbox"
                autotag: no # no | "preview" | "import" | "import_as_is" | "auto"
                # autotag controls what should happen with newly added album folders.
                # no: do nothing
                # "preview": fetch data but do not import (recommended)
                # "import": fetch data and always import (not recommended)
                # "import_as_is": import as is, do not fetch data, but groups albums
                #                 useful for bootlegs, where you manually clean metadata
                #                 and beets wont be able to find any online
                #                 same as `beet import --group-albums -A`
                # "auto": fetch data and import if a good match is found (recommended for established libraries,
                #         but not for a big initial import when you start with beets for the first time)
            Ipsum:
                name: "Dummy inbox"
                path: "/music/dummy"
                autotag: no
